apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-app
spec:
  selector:
    app: sample-nodejs-app
  ports:
  - port: 80
    targetPort: 3000
    protocal: TCP
    name: http
  type: LoadBalancer