apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-app-c
spec:
  selector:
    app: sample-nodejs-app-c
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
